version: '3.8'

services:
  # Family Dashboard App
  app:
    build: .
    container_name: family-dashboard
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./family-data:/app/family-data
      - ./logs:/app/logs
      - ./ssl:/app/ssl:ro
    depends_on:
      - postgres
    networks:
      - family-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: family-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=family_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=family_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - family-network

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: family-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - family-network

  # Redis for sessions (optional)
  redis:
    image: redis:7-alpine
    container_name: family-redis
    restart: unless-stopped
    networks:
      - family-network

volumes:
  postgres_data:

networks:
  family-network:
    driver: bridge